// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InferenceWorkKind } from "./InferenceWorkKind";

export type InferenceWorkStartedNotification = { scopeId: string, rootWorkId: string, workId: string, parentWorkId: string | null, threadId: string, kind: InferenceWorkKind, };
