// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InferenceWorkKind } from "./InferenceWorkKind";
import type { InferenceWorkOutcome } from "./InferenceWorkOutcome";

export type InferenceWorkCompletedNotification = { scopeId: string, rootWorkId: string, workId: string, threadId: string, kind: InferenceWorkKind, outcome: InferenceWorkOutcome, };
